"use client"

import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  PDFDownloadLink,
} from "@react-pdf/renderer"

const styles = StyleSheet.create({

  page: {
    padding: 50,
    fontSize: 11,
    fontFamily: "Helvetica",
  },

  header: {
    marginBottom: 25,
  },

  title: {
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 4,
  },

  subtitle: {
    fontSize: 12,
    color: "#666",
  },

  section: {
    marginBottom: 22,
  },

  sectionTitle: {
    fontSize: 14,
    marginBottom: 10,
    color: "#10B981",
    fontWeight: "bold",
  },

  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 6,
  },

  label: {
    color: "#444",
  },

  value: {
    fontWeight: "bold",
  },

  insightBox: {
    marginTop: 10,
    padding: 10,
    backgroundColor: "#F3F4F6",
  },

  footer: {
    marginTop: 30,
    fontSize: 10,
    color: "#888",
  }

})

function ESGDocument({ records, totalEmission }: any) {

  const electricity = records.reduce(
    (sum: number, r: any) => sum + Number(r.electricity),
    0
  )

  const diesel = records.reduce(
    (sum: number, r: any) => sum + Number(r.diesel),
    0
  )

  const gas = records.reduce(
    (sum: number, r: any) => sum + Number(r.gas),
    0
  )

  const creditsNeeded = (totalEmission / 1000).toFixed(2)

  const reportDate = new Date().toLocaleDateString()

  return (

<Document>

<Page size="A4" style={styles.page}>

{/* HEADER */}

<View style={styles.header}>

<Text style={styles.title}>
CarbonOS Sustainability Report
</Text>

<Text style={styles.subtitle}>
Generated on {reportDate}
</Text>

</View>


{/* EMISSION SUMMARY */}

<View style={styles.section}>

<Text style={styles.sectionTitle}>
Emission Summary
</Text>

<View style={styles.row}>
<Text style={styles.label}>Total Emissions</Text>
<Text style={styles.value}>{totalEmission} kg CO₂</Text>
</View>

<View style={styles.row}>
<Text style={styles.label}>Electricity</Text>
<Text style={styles.value}>{electricity} kg</Text>
</View>

<View style={styles.row}>
<Text style={styles.label}>Diesel</Text>
<Text style={styles.value}>{diesel} kg</Text>
</View>

<View style={styles.row}>
<Text style={styles.label}>Gas</Text>
<Text style={styles.value}>{gas} kg</Text>
</View>

</View>


{/* CARBON OFFSET */}

<View style={styles.section}>

<Text style={styles.sectionTitle}>
Carbon Offset Requirement
</Text>

<View style={styles.row}>
<Text style={styles.label}>Credits Required</Text>
<Text style={styles.value}>{creditsNeeded}</Text>
</View>

</View>


{/* SUSTAINABILITY INSIGHT */}

<View style={styles.section}>

<Text style={styles.sectionTitle}>
Sustainability Insight
</Text>

<View style={styles.insightBox}>

<Text>
Electricity consumption currently contributes the largest share of emissions.
Transitioning to renewable energy sources or improving energy efficiency
could significantly reduce your carbon footprint and operational costs.
</Text>

</View>

</View>


{/* FOOTER */}

<View style={styles.footer}>

<Text>
Generated by CarbonOS Climate Intelligence Platform
</Text>

</View>

</Page>

</Document>

  )
}

export default function ESGReport({ records, totalEmission }: any) {

  return (

<PDFDownloadLink
document={
<ESGDocument
records={records}
totalEmission={totalEmission}
/>
}
fileName="CarbonOS_ESG_Report.pdf"
className="bg-emerald-500 text-black px-4 py-2 rounded-lg font-semibold hover:bg-emerald-600"
>

Download ESG Report

</PDFDownloadLink>

  )
}